const App = (() => {
const STORE="recette19_v4";
const INIT=window.RECETTE19_INITIAL;
const URL="https://application-recette-19.netlify.app";
let db=JSON.parse(localStorage.getItem(STORE)||"null")||structuredClone(INIT);
let current="Toutes", dirty=false;
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const parse=v=>{if(typeof v==="number")return Number.isFinite(v)?v:0;if(v==null)return 0;let s=String(v).trim().replace(/\s/g,"").replace(",",".");if(s===""||s==="-"||s===".")return 0;let n=Number(s);return Number.isFinite(n)?n:0;};
const rnd=(n,d)=>{let p=10**d;return Math.round(parse(n)*p)/p;};
const euro=n=>(parse(n)||0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
const num=(n,d=2)=>(parse(n)||0).toLocaleString("fr-FR",{minimumFractionDigits:d,maximumFractionDigits:d});
function norm(r){if(!r.id)r.id="r"+Date.now()+Math.random();if(!r.family)r.family=db.families[0]||"Pain";if(r.selected===undefined)r.selected=false;if(!r.priceMode)r.priceMode="piece";if(r.costKgHT===undefined)r.costKgHT=r.weightG?rnd(r.costPieceHT*1000/r.weightG,3):0;return r;}
db.recipes.forEach(norm);
function calc(r){norm(r);let t=parse(r.priceTTC),w=parse(r.weightG),vat=parse(r.vat),cost=parse(r.costPieceHT);let kg=w?t*1000/w:0;let ht=t/(1+vat/100);let ckg=w?cost*1000/w:0;let mh=ht-cost;let mt=t-(cost*(1+vat/100));let mp=ht?mh/ht*100:0;let coef=cost?ht/cost:0;return{kg,ht,ckg,mh,mt,mp,coef};}
function sync(r,f){norm(r);["priceTTC","priceKgTTC","weightG","vat","costPieceHT","costKgHT","coef"].includes(f)&&(r[f]=Math.max(0,parse(r[f])));let w=parse(r.weightG),oldKg=parse(r.costKgHT);
if(f==="priceKgTTC"){r.priceMode="kg";r.priceTTC=w?rnd(parse(r.priceKgTTC)*w/1000,2):0;}
if(f==="priceTTC"){r.priceMode="piece";r.priceKgTTC=w?rnd(parse(r.priceTTC)*1000/w,2):0;}
if(f==="costPieceHT")r.costKgHT=w?rnd(parse(r.costPieceHT)*1000/w,3):0;
if(f==="costKgHT")r.costPieceHT=w?rnd(parse(r.costKgHT)*w/1000,3):0;
if(f==="weightG"){if(r.priceMode==="kg")r.priceTTC=w?rnd(parse(r.priceKgTTC)*w/1000,2):0;else r.priceKgTTC=w?rnd(parse(r.priceTTC)*1000/w,2):0;r.costPieceHT=w?rnd(oldKg*w/1000,3):0;}
if(f==="coef"){let ht=parse(r.priceTTC)/(1+parse(r.vat)/100),coef=parse(r.coef);if(coef>0){r.costPieceHT=rnd(ht/coef,3);r.costKgHT=w?rnd(r.costPieceHT*1000/w,3):0;}}
let c=calc(r);r.priceKgTTC=rnd(c.kg,2);r.costKgHT=rnd(c.ckg,3);r.coef=rnd(c.coef,2);}
function dirtyOn(){dirty=true;$("status").textContent="Modifications non sauvegardées";$("status").className="unsaved";}
function save(){localStorage.setItem(STORE,JSON.stringify(db));dirty=false;$("status").textContent="Sauvegardé ✓";$("status").className="saved";}
window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue="";}});
function color(m){return m>=80?"green":m>=75?"orange":"red";}
function setFamily(f){current=f;render();}
function render(){renderTabs();let q=($("search").value||"").toLowerCase().trim();let list=db.recipes.filter(r=>(current==="Toutes"||r.family===current)&&(!q||r.name.toLowerCase().includes(q)||r.family.toLowerCase().includes(q)));let sel=list.filter(r=>r.selected),base=sel.length?sel:list;let sm=base.reduce((a,r)=>a+calc(r).mp,0),mt=base.reduce((a,r)=>a+calc(r).mt,0);$("summary").innerHTML=`<div class="pill">Famille : <b>${esc(current)}</b></div><div class="pill">Recettes : <b>${list.length}</b></div><div class="pill">Sélection : <b>${sel.length}</b></div><div class="pill">Marge moyenne : <b>${base.length?num(sm/base.length,1):"0,0"} %</b></div><div class="pill">100 pièces : <b>${euro(mt*100)}</b></div>`;$("list").innerHTML="";list.forEach(r=>$("list").appendChild(card(r)));}
function renderTabs(){$("tabs").innerHTML="";["Toutes",...db.families].forEach(f=>{let count=f==="Toutes"?db.recipes.length:db.recipes.filter(r=>r.family===f).length;let b=document.createElement("button");b.className=f===current?"active":"";b.textContent=`${f} (${count})`;b.onclick=()=>setFamily(f);$("tabs").appendChild(b);});}
function inp(i,k,l,v,t="number"){return`<div><label>${l}</label><input type="${t}" step="0.001" value="${esc(v)}" onchange="App.update(${i},'${k}',this.value)"></div>`;}
function card(r){let i=db.recipes.indexOf(r),c=calc(r),d=document.createElement("div");d.className="recipe";d.innerHTML=`<div class="top"><input type="checkbox" ${r.selected?"checked":""} onchange="App.update(${i},'selected',this.checked)"><div class="title">${esc(r.name)}</div></div><div class="grid">${inp(i,"name","Nom",r.name,"text")}<div><label>Famille</label><select onchange="App.update(${i},'family',this.value)">${db.families.map(f=>`<option value="${esc(f)}" ${f===r.family?"selected":""}>${esc(f)}</option>`).join("")}</select></div>${inp(i,"priceTTC","Prix TTC",r.priceTTC)}${inp(i,"priceKgTTC","Prix/kg TTC",r.priceKgTTC)}${inp(i,"weightG","Poids g",r.weightG)}${inp(i,"vat","TVA %",r.vat)}<div><label>Prix HT</label><div class="readonly">${euro(c.ht)}</div></div><div><label>Coût/kg HT</label><div class="readonly">${euro(c.ckg)}</div></div>${inp(i,"costPieceHT","Coût pièce HT",r.costPieceHT)}${inp(i,"coef","Coefficient",rnd(c.coef,2))}<div><label>Marge € HT</label><div class="readonly">${euro(c.mh)}</div></div><div><label>Marge € TTC</label><div class="readonly">${euro(c.mt)}</div></div></div><div class="actions"><span class="badge ${color(c.mp)}">${num(c.mp,1)} %</span><div><button class="copy" onclick="App.dup(${i})">Dupliquer</button><button class="danger" onclick="App.del(${i})">Supprimer</button></div></div>`;return d;}
function update(i,k,v){let r=db.recipes[i];if(k==="selected")r.selected=v;else if(k==="name"||k==="family")r[k]=v;else{r[k]=parse(v);sync(r,k);}dirtyOn();render();}
function newFamily(){let f=prompt("Nom de la nouvelle famille");if(!f)return;f=f.trim();if(!f)return;if(!db.families.includes(f))db.families.push(f);current=f;dirtyOn();render();}
function newRecipe(){let n=prompt("Nom de la nouvelle recette","Nouvelle recette");if(!n)return;let fam=current!=="Toutes"?current:(db.families[0]||"Pain");db.recipes.unshift({id:"r"+Date.now(),name:n.trim(),family:fam,selected:false,priceTTC:1,priceKgTTC:4,weightG:250,vat:5.5,costPieceHT:.15,costKgHT:.6,coef:6.35,priceMode:"piece"});current=fam;dirtyOn();render();}
function dup(i){let r=structuredClone(db.recipes[i]);r.id="r"+Date.now();r.name+=" copie";db.recipes.splice(i+1,0,r);dirtyOn();render();}
function del(i){if(confirm("Supprimer cette recette ?")){db.recipes.splice(i,1);dirtyOn();render();}}
function modal(h){$("modalContent").innerHTML=h;$("modal").style.display="flex";}
function closeModal(){$("modal").style.display="none";}
function settings(){modal(`<h2>Paramètres</h2><div class="box"><b>Version 4.0.0</b><br>Lien : <b>https://application-recette-19.netlify.app</b></div><div class="box"><b>Familles</b>${db.families.map(f=>`<div class="row" style="margin-bottom:8px"><div class="grow"><input value="${esc(f)}" onchange="App.renameFamily('${esc(f)}',this.value)"></div><button class="danger" onclick="App.deleteFamily('${esc(f)}')">Supprimer</button></div>`).join("")}</div><div class="box"><b>Données</b><div class="row"><button onclick="App.exportJSON()">Export JSON</button><button onclick="App.exportCSV()">Export CSV</button><label class="uploadBtn">Import JSON<input type="file" accept=".json" onchange="App.importJSON(event)"></label></div></div><button class="secondary" onclick="App.closeModal()">Fermer</button>`);}
function renameFamily(o,n){n=(n||"").trim();if(!n||o===n)return;if(db.families.includes(n))return alert("Cette famille existe déjà.");db.families=db.families.map(f=>f===o?n:f);db.recipes.forEach(r=>{if(r.family===o)r.family=n;});current=n;dirtyOn();settings();render();}
function deleteFamily(f){if(db.families.length<=1)return alert("Il faut garder une famille.");let t=prompt("Déplacer les recettes vers quelle famille ?",db.families.find(x=>x!==f)||"Pain");if(!t)return;if(!db.families.includes(t))db.families.push(t);db.recipes.forEach(r=>{if(r.family===f)r.family=t;});db.families=db.families.filter(x=>x!==f);current="Toutes";dirtyOn();settings();render();}
function share(){modal(`<h2>Partager</h2><div class="box">Lien officiel :<br><b>https://application-recette-19.netlify.app</b></div><div style="text-align:center"><img class="qr" src="https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=https://application-recette-19.netlify.app"></div><div class="row"><button onclick="App.shareLink()">Partager</button><button class="secondary" onclick="App.copyLink()">Copier</button><button class="secondary" onclick="App.closeModal()">Fermer</button></div><p id="modalInfo" class="small"></p>`);}
async function shareLink(){if(navigator.share){try{await navigator.share({title:"Application Recette 19",text:"Calculateur de prix de revient et marge.",url:URL});}catch(e){}}else copyLink();}
function copyLink(){navigator.clipboard?.writeText(`Application Recette 19\n${URL}`);let i=document.getElementById("modalInfo");if(i)i.textContent="Lien copié.";}
function exportJSON(){let b=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="sauvegarde_recette19.json";a.click();}
function importJSON(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);db.recipes.forEach(norm);dirtyOn();closeModal();render();alert("Import terminé. Clique sur Sauvegarder.");}catch(err){alert("Fichier invalide.");}};r.readAsText(f);}
function exportCSV(){let rows=[["Famille","Selection","Nom","Prix TTC","Prix/kg TTC","Poids","Prix HT","Cout piece HT","Cout/kg HT","Marge %","Marge HT","Marge TTC","Coef"]];db.recipes.forEach(r=>{let c=calc(r);rows.push([r.family,r.selected?"Oui":"Non",r.name,r.priceTTC,r.priceKgTTC,r.weightG,c.ht,r.costPieceHT,c.ckg,c.mp,c.mh,c.mt,c.coef]);});let csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(";")).join("\n"),b=new Blob([csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="recette19.csv";a.click();}
if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./service-worker.js").catch(()=>{});
render();
return{render,setFamily,save,newFamily,newRecipe,update,dup,del,settings,closeModal,renameFamily,deleteFamily,share,shareLink,copyLink,exportJSON,importJSON,exportCSV};
})();
