
const App=(()=>{
const FIREBASE_CONFIG={apiKey:"AIzaSyASWj-YPKjhpERSkMsacGqPI5pdlYcXvxY",authDomain:"application-recette-19.firebaseapp.com",projectId:"application-recette-19",storageBucket:"application-recette-19.firebasestorage.app",messagingSenderId:"458649313152",appId:"1:458649313152:web:cb64dcf459298902ae2b65",measurementId:"G-TRF852J7J5"};
const STORE="recette19_v10_donnees_protegees",ACCESS_STORE="recette19_access_v10",ADMIN_PIN="1919";
const LEGACY=["recette19_v10_donnees_protegees","recette19_v8_donnees_protegees","recette19_donnees_utilisateur_stables_v7","recette19_donnees_stables","recette19_v6","recette19_v52","recette19_v51","recette19_v5","recette19_v4"];
const INIT=window.RECETTE19_INITIAL||{},URL=INIT.officialUrl||"https://application-recette-19.netlify.app";
let current="Toutes",saveTimer=null,mode="admin",firestore=null,ready=false;
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const parse=v=>{if(typeof v==="number")return Number.isFinite(v)?v:0;let s=String(v??"").trim().replace(/\s/g,"").replace(",",".");let n=Number(s);return Number.isFinite(n)?n:0};
const rnd=(n,d)=>Math.round(parse(n)*10**d)/10**d;
const euro=n=>(parse(n)||0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
const num=(n,d=2)=>(parse(n)||0).toLocaleString("fr-FR",{minimumFractionDigits:d,maximumFractionDigits:d});
function msg(t){const st=$("accessStatus");if(st)st.textContent=t;console.log("[Recette19]",t)}
function normalizeName(v){return String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function getDeviceId(){let id=localStorage.getItem("recette19_device_id");if(!id){id="dev-"+Date.now()+"-"+Math.random().toString(16).slice(2);localStorage.setItem("recette19_device_id",id)}return id}
function getAccess(){try{return JSON.parse(localStorage.getItem(ACCESS_STORE)||"{}")}catch(e){return{}}}
function setAccess(a){localStorage.setItem(ACCESS_STORE,JSON.stringify(a||{}))}
function initFirebase(){try{if(!window.firebase){msg("Firebase SDK non chargé.");return false}if(!firebase.apps.length)firebase.initializeApp(FIREBASE_CONFIG);firestore=firebase.firestore();ready=true;return true}catch(e){msg("Erreur Firebase : "+(e.message||e));return false}}
function loadDB(){for(const k of LEGACY){let raw=localStorage.getItem(k);if(raw){try{let d=JSON.parse(raw);if(d&&Array.isArray(d.recipes)&&Array.isArray(d.families)){localStorage.setItem(STORE,JSON.stringify(d));return d}}catch(e){}}}return structuredClone(INIT)}
let db=loadDB();
function norm(r){if(!r.id)r.id="recette19-user-"+Date.now()+"-"+Math.random().toString(16).slice(2);if(!r.family)r.family=(db.families&&db.families[0])||"Pain";if(r.selected===undefined)r.selected=false;if(r.publish===undefined)r.publish=false;if(!r.source)r.source=String(r.id).includes("official")?"officielle":"personnelle";if(!r.recipeVersion)r.recipeVersion=1;if(!r.priceMode)r.priceMode="piece";if(r.costKgHT===undefined)r.costKgHT=r.weightG?rnd(r.costPieceHT*1000/r.weightG,3):0;return r}
function mergeOfficialData(){if(!db.families)db.families=[];if(!db.recipes)db.recipes=[];(INIT.families||[]).forEach(f=>{if(!db.families.includes(f))db.families.push(f)});const byId=new Map(db.recipes.map(r=>[String(r.id||""),r]));const byNameFam=new Map(db.recipes.map(r=>[`${String(r.name||"").toLowerCase()}||${String(r.family||"").toLowerCase()}`,r]));(INIT.recipes||[]).forEach(o=>{norm(o);o.source="officielle";let key=`${String(o.name||"").toLowerCase()}||${String(o.family||"").toLowerCase()}`;let ex=byId.get(String(o.id))||byNameFam.get(key);if(!ex){let c=structuredClone(o);c.selected=false;c.publish=false;db.recipes.push(c)}});db.version=INIT.version||"10.0.0";db.officialUrl=URL;db.storageMode="protected-user-data-v10";db.recipes.forEach(norm)}
mergeOfficialData();
function calc(r){norm(r);let t=parse(r.priceTTC),w=parse(r.weightG),vat=parse(r.vat),cost=parse(r.costPieceHT),kg=w?t*1000/w:0,ht=t/(1+vat/100),ckg=w?cost*1000/w:0,mh=ht-cost,mt=t-cost*(1+vat/100),mp=ht?mh/ht*100:0,coef=cost?ht/cost:0;return{kg,ht,ckg,mh,mt,mp,coef}}
function sync(r,f){norm(r);["priceTTC","priceKgTTC","weightG","vat","costPieceHT","costKgHT","coef"].includes(f)&&(r[f]=Math.max(0,parse(r[f])));let w=parse(r.weightG),oldKg=parse(r.costKgHT);if(f==="priceKgTTC"){r.priceMode="kg";r.priceTTC=w?rnd(parse(r.priceKgTTC)*w/1000,2):0}if(f==="priceTTC"){r.priceMode="piece";r.priceKgTTC=w?rnd(parse(r.priceTTC)*1000/w,2):0}if(f==="costPieceHT")r.costKgHT=w?rnd(parse(r.costPieceHT)*1000/w,3):0;if(f==="costKgHT")r.costPieceHT=w?rnd(parse(r.costKgHT)*w/1000,3):0;if(f==="weightG"){if(r.priceMode==="kg")r.priceTTC=w?rnd(parse(r.priceKgTTC)*w/1000,2):0;else r.priceKgTTC=w?rnd(parse(r.priceTTC)*1000/w,2):0;r.costPieceHT=w?rnd(oldKg*w/1000,3):0}if(f==="coef"){let ht=parse(r.priceTTC)/(1+parse(r.vat)/100),coef=parse(r.coef);if(coef>0){r.costPieceHT=rnd(ht/coef,3);r.costKgHT=w?rnd(r.costPieceHT*1000/w,3):0}}let c=calc(r);r.priceKgTTC=rnd(c.kg,2);r.costKgHT=rnd(c.ckg,3);r.coef=rnd(c.coef,2)}
function save(){localStorage.setItem(STORE,JSON.stringify(db));const st=$("status");if(st){st.textContent="Sauvegardé automatiquement ✓";st.className="saved"}}
function autoSave(){clearTimeout(saveTimer);const st=$("status");if(st){st.textContent="Sauvegarde en cours...";st.className="unsaved"}saveTimer=setTimeout(save,250)}
function color(m){return m>=80?"green":m>=75?"orange":"red"}
async function requestAccess(){const input=$("bakeryNameInput"),name=(input?.value||"").trim();if(!name){msg("Renseignez le nom de la boulangerie.");return}if(!ready&&!initFirebase())return;const bakeryId=normalizeName(name)+"-"+getDeviceId().slice(-6);try{msg("Envoi de la demande...");await firestore.collection("demandes_acces").doc(bakeryId).set({bakeryName:name,bakeryId,deviceId:getDeviceId(),status:"en_attente",createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});setAccess({bakeryName:name,bakeryId,status:"en_attente"});msg("Demande envoyée. Attente de l’autorisation Minoterie 19.")}catch(e){msg("Erreur d’envoi : "+(e.message||e))}}
async function checkAccess(){const gate=$("accessGate"),main=$("mainApp");if(!ready&&!initFirebase()){if(gate)gate.style.display="flex";if(main)main.style.display="none";return false}const a=getAccess();if(!a.bakeryId){if(gate)gate.style.display="flex";if(main)main.style.display="none";msg("Saisissez le nom de la boulangerie puis demandez l'accès.");return false}try{msg("Vérification en cours...");const doc=await firestore.collection("demandes_acces").doc(a.bakeryId).get();if(doc.exists&&doc.data().status==="autorise"){setAccess({...a,status:"autorise"});if(gate)gate.style.display="none";if(main)main.style.display="block";render();return true}if(gate)gate.style.display="flex";if(main)main.style.display="none";msg(doc.exists&&doc.data().status==="refuse"?"Accès refusé. Contactez Minoterie 19.":"Demande envoyée. En attente d’autorisation.");return false}catch(e){msg("Erreur vérification : "+(e.message||e));return false}}
function renderFamilies(){let box=$("familiesList");if(!box)return;box.innerHTML="";["Toutes",...db.families].forEach(f=>{let count=f==="Toutes"?db.recipes.length:db.recipes.filter(r=>r.family===f).length;let line=document.createElement("div");line.className="familyLine";let main=document.createElement("button");main.className="familyBtn "+(f===current?"active":"");main.innerHTML=`<span>${esc(f)}</span><b>${count}</b>`;main.onclick=()=>{current=f;render()};line.appendChild(main);if(f!=="Toutes"&&mode==="admin"){let edit=document.createElement("button");edit.className="secondary smallBtn";edit.textContent="✏️";edit.onclick=()=>renameFamilyPrompt(f);let del=document.createElement("button");del.className="danger smallBtn";del.textContent="🗑";del.onclick=()=>deleteFamily(f);line.appendChild(edit);line.appendChild(del)}else{line.appendChild(document.createElement("span"));line.appendChild(document.createElement("span"))}box.appendChild(line)})}
function render(){renderFamilies();let q=($("search")?.value||"").toLowerCase().trim();let list=db.recipes.filter(r=>(current==="Toutes"||r.family===current)&&(!q||r.name.toLowerCase().includes(q)||r.family.toLowerCase().includes(q)));let sel=list.filter(r=>r.selected),pub=list.filter(r=>r.publish),base=sel.length?sel:list,sm=base.reduce((a,r)=>a+calc(r).mp,0),mt=base.reduce((a,r)=>a+calc(r).mt,0);if($("summary"))$("summary").innerHTML=`<div class="pill">Mode : <b>${mode==="admin"?"Admin":"Utilisateur"}</b></div><div class="pill">Famille : <b>${esc(current)}</b></div><div class="pill">Recettes : <b>${list.length}</b></div><div class="pill">Sélection marge : <b>${sel.length}</b></div><div class="pill">À publier : <b>${pub.length}</b></div><div class="pill">Marge moyenne : <b>${base.length?num(sm/base.length,1):"0,0"} %</b></div><div class="pill">100 pièces : <b>${euro(mt*100)}</b></div>`;let lb=$("list");if(!lb)return;lb.innerHTML="";list.forEach(r=>lb.appendChild(card(r)))}
function inp(i,k,l,v,t="number"){return`<div><label>${l}</label><input type="${t}" step="0.001" value="${esc(v)}" onchange="App.update(${i},'${k}',this.value)"></div>`}
function card(r){let i=db.recipes.indexOf(r),c=calc(r),d=document.createElement("div");d.className="recipe";let publishBox=mode==="admin"?`<label class="checkItem"><input type="checkbox" ${r.publish?"checked":""} onchange="App.update(${i},'publish',this.checked)"> À publier</label>`:"";d.innerHTML=`<div class="checks"><label class="checkItem"><input type="checkbox" ${r.selected?"checked":""} onchange="App.update(${i},'selected',this.checked)"> Sélection marge</label>${publishBox}</div><div class="recipeTitleBox"><input value="${esc(r.name)}" onchange="App.update(${i},'name',this.value)"></div><div class="grid"><div><label>Famille</label><select onchange="App.update(${i},'family',this.value)">${db.families.map(f=>`<option value="${esc(f)}" ${f===r.family?"selected":""}>${esc(f)}</option>`).join("")}</select></div>${inp(i,"priceTTC","Prix TTC",r.priceTTC)}${inp(i,"priceKgTTC","Prix/kg TTC",r.priceKgTTC)}${inp(i,"weightG","Poids g",r.weightG)}${inp(i,"vat","TVA %",r.vat)}<div><label>Prix HT</label><div class="readonly">${euro(c.ht)}</div></div><div><label>Coût/kg HT</label><div class="readonly">${euro(c.ckg)}</div></div>${inp(i,"costPieceHT","Coût pièce HT",r.costPieceHT)}${inp(i,"coef","Coefficient",rnd(c.coef,2))}<div><label>Marge € HT</label><div class="readonly">${euro(c.mh)}</div></div><div><label>Marge € TTC</label><div class="readonly">${euro(c.mt)}</div></div></div><div class="actions"><span class="badge ${color(c.mp)}">${num(c.mp,1)} %</span><div><button class="copy" onclick="App.dup(${i})">Dupliquer</button><button class="danger" onclick="App.del(${i})">Supprimer</button></div></div>`;return d}
function update(i,k,v){let r=db.recipes[i];if(k==="selected"||k==="publish")r[k]=v;else if(k==="name"||k==="family")r[k]=v;else{r[k]=parse(v);sync(r,k)}autoSave();render()}
function newFamily(){let f=prompt("Nom de la nouvelle famille");if(!f)return;f=f.trim();if(!f)return;if(db.families.includes(f))return alert("Cette famille existe déjà.");db.families.push(f);current=f;autoSave();render()}
function renameFamilyPrompt(o){let n=prompt("Nouveau nom de la famille",o);if(n)renameFamily(o,n)}
function renameFamily(o,n){n=(n||"").trim();if(!n||o===n)return;if(db.families.includes(n))return alert("Cette famille existe déjà.");if(!confirm(`Renommer la famille "${o}" en "${n}" ?`))return;db.families=db.families.map(f=>f===o?n:f);db.recipes.forEach(r=>{if(r.family===o)r.family=n});if(current===o)current=n;autoSave();render()}
function deleteFamily(f){let count=db.recipes.filter(r=>r.family===f).length;if(!confirm(`Confirmer la suppression de la famille "${f}" ?`))return;if(count>0){let others=db.families.filter(x=>x!==f);if(!others.length)return alert("Crée une autre famille avant.");let target=prompt(`Cette famille contient ${count} recette(s). Vers quelle famille déplacer ?`,others[0]);if(!target)return;if(!db.families.includes(target))db.families.push(target);db.recipes.forEach(r=>{if(r.family===f)r.family=target})}db.families=db.families.filter(x=>x!==f);current="Toutes";autoSave();render()}
function newRecipe(){let n=prompt("Nom de la nouvelle recette","Nouvelle recette");if(!n)return;let fam=current!=="Toutes"?current:(db.families[0]||"Pain");db.recipes.unshift({id:"recette19-user-"+Date.now(),source:"personnelle",recipeVersion:1,name:n.trim(),family:fam,selected:false,publish:false,priceTTC:1,priceKgTTC:4,weightG:250,vat:5.5,costPieceHT:.15,costKgHT:.6,coef:6.35,priceMode:"piece"});current=fam;autoSave();render()}
function dup(i){let r=structuredClone(db.recipes[i]);r.id="recette19-user-"+Date.now();r.name+=" copie";r.source="personnelle";r.publish=false;db.recipes.splice(i+1,0,r);autoSave();render()}
function del(i){let r=db.recipes[i];if(confirm(`Confirmer la suppression de la recette "${r.name}" ?`)){db.recipes.splice(i,1);autoSave();render()}}
function modal(h){$("modalContent").innerHTML=h;$("modal").style.display="flex"}function closeModal(){$("modal").style.display="none"}
async function openAdmin(){let pin=prompt("Code administrateur");if(pin!=="1919")return alert("Code incorrect.");if(!ready&&!initFirebase())return alert("Firebase non disponible.");modal('<h2>Administration des accès</h2><div class="box"><b>Demandes d’accès</b></div><div id="adminList">Chargement...</div><button class="secondary" onclick="App.closeModal()">Fermer</button>');let list=$("adminList");try{let snap=await firestore.collection("demandes_acces").orderBy("createdAt","desc").limit(50).get();if(snap.empty){list.innerHTML="<p>Aucune demande.</p>";return}list.innerHTML="";snap.forEach(doc=>{let d=doc.data();let row=document.createElement("div");row.className="adminLine";row.innerHTML=`<div><b>${esc(d.bakeryName||doc.id)}</b><div class="adminStatus">${esc(d.status||"en_attente")}<br>${esc(doc.id)}</div></div><button class="ok" onclick="App.authorizeAccess('${doc.id}')">Autoriser</button><button class="danger" onclick="App.refuseAccess('${doc.id}')">Refuser</button>`;list.appendChild(row)})}catch(e){list.innerHTML="<p>Erreur : "+esc(e.message||e)+"</p>"}}
async function authorizeAccess(id){await firestore.collection("demandes_acces").doc(id).set({status:"autorise",updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});alert("Accès autorisé.");openAdmin()}
async function refuseAccess(id){if(!confirm("Refuser cet accès ?"))return;await firestore.collection("demandes_acces").doc(id).set({status:"refuse",updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});alert("Accès refusé.");openAdmin()}
function openPublish(){let selected=db.recipes.filter(r=>r.publish);modal(`<h2>Créer une mise à jour</h2><div class="box publish"><b>${selected.length} recette(s) cochée(s)</b></div><div class="box">${selected.map(r=>`• ${esc(r.family)} — ${esc(r.name)}`).join("<br>")||"Aucune recette cochée."}</div><div class="row"><button onclick="App.exportUpdate()">Créer fichier</button><label class="uploadBtn">Importer mise à jour<input type="file" accept=".json" onchange="App.importUpdate(event)"></label><button class="secondary" onclick="App.closeModal()">Fermer</button></div>`)}
function exportUpdate(){let selected=db.recipes.filter(r=>r.publish);if(!selected.length)return alert("Aucune recette cochée.");let pack={type:"recette19-update",createdAt:new Date().toISOString(),families:[...new Set(selected.map(r=>r.family))],recipes:selected.map(r=>structuredClone(r))};pack.recipes.forEach(r=>{r.publish=false;r.selected=false});downloadJSON(pack,"mise_a_jour_recettes_19.json")}
function importUpdate(e){readJSON(e,pack=>{if(pack.type!=="recette19-update"||!pack.recipes)return alert("Fichier invalide.");let added=0;pack.families?.forEach(f=>{if(!db.families.includes(f))db.families.push(f)});pack.recipes.forEach(nr=>{norm(nr);nr.publish=false;nr.selected=false;if(!db.recipes.find(r=>r.id===nr.id)){db.recipes.push(nr);added++}});save();closeModal();render();alert(`${added} recette(s) ajoutée(s).`)})}
function openClientSend(){let options=db.recipes.map((r,i)=>`<option value="${i}">${esc(r.family)} — ${esc(r.name)}</option>`).join("");modal(`<h2>Envoyer recette client</h2><div class="box"><select id="clientRecipeSelect">${options}</select></div><div class="row"><button onclick="App.exportClientRecipe()">Créer fichier JSON</button><button class="copy" onclick="App.shareClientRecipeText()">Partager résumé</button><button class="secondary" onclick="App.closeModal()">Fermer</button></div>`)}
function exportClientRecipe(){let r=db.recipes[parse($("clientRecipeSelect")?.value)];if(!r)return;downloadJSON({type:"recette19-client-recipe",createdAt:new Date().toISOString(),recipe:structuredClone(r)},"recette_client_"+String(r.name).replace(/[^a-z0-9-_]+/gi,"_")+".json")}
async function shareClientRecipeText(){let r=db.recipes[parse($("clientRecipeSelect")?.value)];if(!r)return;let c=calc(r);let text=`Recette client\nFamille : ${r.family}\nNom : ${r.name}\nPrix TTC : ${r.priceTTC}\nPoids : ${r.weightG} g\nMarge : ${num(c.mp,1)} %`;if(navigator.share)await navigator.share({title:"Recette client",text});else navigator.clipboard?.writeText(text)}
function settings(){modal(`<h2>Paramètres</h2><div class="box"><b>Version ${INIT.version||"10.0.0"}</b><br>Données protégées V10.</div><div class="box"><b>Mode</b><div class="row"><button onclick="App.setMode('admin')">Mode Admin</button><button class="secondary" onclick="App.setMode('user')">Mode Utilisateur</button></div></div><div class="box"><div class="row"><button onclick="App.exportJSON()">Sauvegarde JSON</button><label class="uploadBtn">Restaurer JSON<input type="file" accept=".json" onchange="App.importJSON(event)"></label><button onclick="App.exportCSV()">Export CSV</button></div></div><button class="secondary" onclick="App.closeModal()">Fermer</button>`)}
function setMode(m){mode=m==="user"?"user":"admin";closeModal();render();autoSave()}
function share(){modal(`<h2>Partager</h2><div class="box">${URL}</div><button onclick="App.shareLink()">Partager le lien</button><button class="secondary" onclick="App.closeModal()">Fermer</button>`)}
async function shareLink(){if(navigator.share)await navigator.share({title:"Application Recette 19",url:URL});else navigator.clipboard?.writeText(URL)}
function exportJSON(){save();downloadJSON(db,"sauvegarde_complete_recette19.json")}function importJSON(e){readJSON(e,d=>{if(!d.recipes||!d.families)return alert("Fichier invalide.");db=d;db.recipes.forEach(norm);save();closeModal();render();alert("Sauvegarde restaurée.")})}
function exportCSV(){let rows=[["Famille","Nom","Prix TTC","Poids","Cout HT","Marge %"]];db.recipes.forEach(r=>{let c=calc(r);rows.push([r.family,r.name,r.priceTTC,r.weightG,r.costPieceHT,c.mp])});let csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(";")).join("\n");downloadBlob(csv,"recette19.csv","text/csv;charset=utf-8")}
function downloadJSON(obj,name){downloadBlob(JSON.stringify(obj,null,2),name,"application/json")}function downloadBlob(content,name,type){let b=new Blob([content],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click()}
function readJSON(e,cb){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{cb(JSON.parse(r.result))}catch(err){alert("Fichier invalide.")}};r.readAsText(f)}
function installHelp(){modal(`<h2>Installer l’application</h2><div class="box"><b>iPhone</b><br>Safari → Partager → Sur l’écran d’accueil.</div><div class="box"><b>Samsung / Android</b><br>Chrome → ⋮ → Ajouter à l’écran d’accueil.</div><button class="secondary" onclick="App.closeModal()">Fermer</button>`)}
function hideInstall(){$("installBox").style.display="none";localStorage.setItem("recette19_install_hidden","1")}
if(localStorage.getItem("recette19_install_hidden")==="1"&&$("installBox"))$("installBox").style.display="none";
if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./service-worker.js").catch(()=>{});
save();initFirebase();setTimeout(checkAccess,700);
return{render,save,newFamily,newRecipe,update,dup,del,settings,closeModal,renameFamily,renameFamilyPrompt,deleteFamily,share,shareLink,exportJSON,importJSON,exportCSV,installHelp,hideInstall,openPublish,exportUpdate,importUpdate,openClientSend,exportClientRecipe,shareClientRecipeText,setMode,requestAccess,checkAccess,openAdmin,authorizeAccess,refuseAccess};
})();
