window.RECETTE19_INITIAL = {
  "version": "4.0.0",
  "officialUrl": "https://application-recette-19.netlify.app",
  "families": [
    "Pain",
    "Pain spécial",
    "Bio",
    "Viennoiserie",
    "Pâtisserie"
  ],
  "recipes": [
    {
      "id": "r1",
      "name": "Gustive pain courant",
      "family": "Pain",
      "selected": false,
      "priceTTC": 1.0,
      "priceKgTTC": 4.0,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.141,
      "costKgHT": 0.565,
      "coef": 6.71,
      "priceMode": "piece"
    },
    {
      "id": "r2",
      "name": "Gustive chef",
      "family": "Pain",
      "selected": false,
      "priceTTC": 1.1,
      "priceKgTTC": 4.4,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.155,
      "costKgHT": 0.621,
      "coef": 6.71,
      "priceMode": "piece"
    },
    {
      "id": "r3",
      "name": "TF Gustive, TF 19",
      "family": "Pain",
      "selected": false,
      "priceTTC": 1.15,
      "priceKgTTC": 4.6,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.161,
      "costKgHT": 0.645,
      "coef": 6.76,
      "priceMode": "piece"
    },
    {
      "id": "r4",
      "name": "Tradition T80",
      "family": "Pain",
      "selected": false,
      "priceTTC": 1.2,
      "priceKgTTC": 4.8,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.181,
      "costKgHT": 0.723,
      "coef": 6.29,
      "priceMode": "piece"
    },
    {
      "id": "r5",
      "name": "T65",
      "family": "Pain",
      "selected": false,
      "priceTTC": 0.95,
      "priceKgTTC": 3.8,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.14,
      "costKgHT": 0.558,
      "coef": 6.45,
      "priceMode": "piece"
    },
    {
      "id": "r6",
      "name": "T80",
      "family": "Pain",
      "selected": false,
      "priceTTC": 1.4,
      "priceKgTTC": 4.67,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.227,
      "costKgHT": 0.756,
      "coef": 5.85,
      "priceMode": "piece"
    },
    {
      "id": "r7",
      "name": "Gustive Graines",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.3,
      "priceKgTTC": 5.2,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.208,
      "costKgHT": 0.833,
      "coef": 5.92,
      "priceMode": "piece"
    },
    {
      "id": "r8",
      "name": "Campagne",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.7,
      "priceKgTTC": 5.67,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.255,
      "costKgHT": 0.849,
      "coef": 6.33,
      "priceMode": "piece"
    },
    {
      "id": "r9",
      "name": "Complet",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.7,
      "priceKgTTC": 5.67,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.255,
      "costKgHT": 0.849,
      "coef": 6.33,
      "priceMode": "piece"
    },
    {
      "id": "r10",
      "name": "Gustigrain",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 2.15,
      "priceKgTTC": 7.17,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.42,
      "costKgHT": 1.399,
      "coef": 4.85,
      "priceMode": "piece"
    },
    {
      "id": "r11",
      "name": "Oslo",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 2.5,
      "priceKgTTC": 8.33,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.472,
      "costKgHT": 1.572,
      "coef": 5.03,
      "priceMode": "piece"
    },
    {
      "id": "r12",
      "name": "6 céréales",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.9,
      "priceKgTTC": 6.33,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.362,
      "costKgHT": 1.207,
      "coef": 4.98,
      "priceMode": "piece"
    },
    {
      "id": "r13",
      "name": "Spécial Seigle",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.8,
      "priceKgTTC": 6.0,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.311,
      "costKgHT": 1.035,
      "coef": 5.49,
      "priceMode": "piece"
    },
    {
      "id": "r14",
      "name": "Pavé Louis",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.7,
      "priceKgTTC": 5.67,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.327,
      "costKgHT": 1.09,
      "coef": 4.93,
      "priceMode": "piece"
    },
    {
      "id": "r15",
      "name": "Grigneton",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.4,
      "priceKgTTC": 5.6,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.264,
      "costKgHT": 1.056,
      "coef": 5.03,
      "priceMode": "piece"
    },
    {
      "id": "r16",
      "name": "Ancestral",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.7,
      "priceKgTTC": 6.8,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.392,
      "costKgHT": 1.566,
      "coef": 4.12,
      "priceMode": "piece"
    },
    {
      "id": "r17",
      "name": "Graines Champion",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.7,
      "priceKgTTC": 6.8,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.353,
      "costKgHT": 1.412,
      "coef": 4.57,
      "priceMode": "piece"
    },
    {
      "id": "r18",
      "name": "Spécial Maïs",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 2.35,
      "priceKgTTC": 7.83,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.47,
      "costKgHT": 1.567,
      "coef": 4.74,
      "priceMode": "piece"
    },
    {
      "id": "r19",
      "name": "Cafino",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 2.0,
      "priceKgTTC": 6.67,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.389,
      "costKgHT": 1.295,
      "coef": 4.88,
      "priceMode": "piece"
    },
    {
      "id": "r20",
      "name": "Cafino acidulé",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 3.5,
      "priceKgTTC": 11.67,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.703,
      "costKgHT": 2.344,
      "coef": 4.72,
      "priceMode": "piece"
    },
    {
      "id": "r21",
      "name": "Baguettes aux graines ou pavé",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.6,
      "priceKgTTC": 6.4,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.322,
      "costKgHT": 1.286,
      "coef": 4.72,
      "priceMode": "piece"
    },
    {
      "id": "r22",
      "name": "Gatine",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.3,
      "priceKgTTC": 5.2,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.202,
      "costKgHT": 0.808,
      "coef": 6.1,
      "priceMode": "piece"
    },
    {
      "id": "r23",
      "name": "Bleu Blanc Cœur",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.5,
      "priceKgTTC": 6.0,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.301,
      "costKgHT": 1.206,
      "coef": 4.72,
      "priceMode": "piece"
    },
    {
      "id": "r24",
      "name": "Le Zen",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 2.8,
      "priceKgTTC": 9.33,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.653,
      "costKgHT": 2.176,
      "coef": 4.07,
      "priceMode": "piece"
    },
    {
      "id": "r25",
      "name": "Fermier",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 2.8,
      "priceKgTTC": 7.0,
      "weightG": 400,
      "vat": 5.5,
      "costPieceHT": 0.483,
      "costKgHT": 1.208,
      "coef": 5.49,
      "priceMode": "piece"
    },
    {
      "id": "r26",
      "name": "RustiMeule T110",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.5,
      "priceKgTTC": 3.75,
      "weightG": 400,
      "vat": 5.5,
      "costPieceHT": 0.257,
      "costKgHT": 0.643,
      "coef": 5.52,
      "priceMode": "piece"
    },
    {
      "id": "r27",
      "name": "Epeautre",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 2.2,
      "priceKgTTC": 7.33,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.463,
      "costKgHT": 1.543,
      "coef": 4.5,
      "priceMode": "piece"
    },
    {
      "id": "r28",
      "name": "Muesli (base Tradition ou Gustive)",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 3.2,
      "priceKgTTC": 10.67,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.625,
      "costKgHT": 2.083,
      "coef": 4.85,
      "priceMode": "piece"
    },
    {
      "id": "r29",
      "name": "Royal (base Tradition ou Gustive)",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 3.2,
      "priceKgTTC": 10.67,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.67,
      "costKgHT": 2.234,
      "coef": 4.52,
      "priceMode": "piece"
    },
    {
      "id": "r30",
      "name": "Impérial (base Tradition ou Gustive)",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 3.0,
      "priceKgTTC": 10.0,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.569,
      "costKgHT": 1.896,
      "coef": 5.0,
      "priceMode": "piece"
    },
    {
      "id": "r31",
      "name": "Figue Chataîgne Noisette",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 2.5,
      "priceKgTTC": 10.0,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.502,
      "costKgHT": 2.009,
      "coef": 4.72,
      "priceMode": "piece"
    },
    {
      "id": "r32",
      "name": "pavé Figues abricot",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 3.0,
      "priceKgTTC": 10.0,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.631,
      "costKgHT": 2.104,
      "coef": 4.5,
      "priceMode": "piece"
    },
    {
      "id": "r33",
      "name": "Acidulé (base Tradition ou Gustive)",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 2.8,
      "priceKgTTC": 9.33,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.467,
      "costKgHT": 1.557,
      "coef": 5.68,
      "priceMode": "piece"
    },
    {
      "id": "r34",
      "name": "Saveur d'anjou",
      "family": "Pain spécial",
      "selected": false,
      "priceTTC": 1.2,
      "priceKgTTC": 4.8,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.188,
      "costKgHT": 0.751,
      "coef": 6.06,
      "priceMode": "piece"
    },
    {
      "id": "r35",
      "name": "Pain d'épices",
      "family": "Pâtisserie",
      "selected": false,
      "priceTTC": 6.0,
      "priceKgTTC": 21.43,
      "weightG": 280,
      "vat": 5.5,
      "costPieceHT": 1.359,
      "costKgHT": 4.854,
      "coef": 4.18,
      "priceMode": "piece"
    },
    {
      "id": "r36",
      "name": "BIO T65",
      "family": "Bio",
      "selected": false,
      "priceTTC": 1.25,
      "priceKgTTC": 5.0,
      "weightG": 250,
      "vat": 5.5,
      "costPieceHT": 0.222,
      "costKgHT": 0.886,
      "coef": 5.35,
      "priceMode": "piece"
    },
    {
      "id": "r37",
      "name": "BIO T110 meule",
      "family": "Bio",
      "selected": false,
      "priceTTC": 2.0,
      "priceKgTTC": 5.0,
      "weightG": 400,
      "vat": 5.5,
      "costPieceHT": 0.32,
      "costKgHT": 0.801,
      "coef": 5.92,
      "priceMode": "piece"
    },
    {
      "id": "r38",
      "name": "BIO T150 meule",
      "family": "Bio",
      "selected": false,
      "priceTTC": 1.6,
      "priceKgTTC": 5.33,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.238,
      "costKgHT": 0.794,
      "coef": 6.37,
      "priceMode": "piece"
    },
    {
      "id": "r39",
      "name": "BIO Grand épeautre",
      "family": "Bio",
      "selected": false,
      "priceTTC": 3.0,
      "priceKgTTC": 7.5,
      "weightG": 400,
      "vat": 5.5,
      "costPieceHT": 0.677,
      "costKgHT": 1.692,
      "coef": 4.2,
      "priceMode": "piece"
    },
    {
      "id": "r40",
      "name": "BIO petit épeautre",
      "family": "Bio",
      "selected": false,
      "priceTTC": 3.6,
      "priceKgTTC": 12.0,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.679,
      "costKgHT": 2.264,
      "coef": 5.03,
      "priceMode": "piece"
    },
    {
      "id": "r41",
      "name": "BIO Seigle T170",
      "family": "Bio",
      "selected": false,
      "priceTTC": 1.9,
      "priceKgTTC": 4.75,
      "weightG": 400,
      "vat": 5.5,
      "costPieceHT": 0.324,
      "costKgHT": 0.81,
      "coef": 5.56,
      "priceMode": "piece"
    },
    {
      "id": "r42",
      "name": "BIO Khorasan",
      "family": "Bio",
      "selected": false,
      "priceTTC": 3.8,
      "priceKgTTC": 12.67,
      "weightG": 300,
      "vat": 5.5,
      "costPieceHT": 0.699,
      "costKgHT": 2.329,
      "coef": 5.15,
      "priceMode": "piece"
    },
    {
      "id": "r43",
      "name": "BIO blé ancien",
      "family": "Bio",
      "selected": false,
      "priceTTC": 2.8,
      "priceKgTTC": 7.0,
      "weightG": 400,
      "vat": 5.5,
      "costPieceHT": 0.541,
      "costKgHT": 1.354,
      "coef": 4.9,
      "priceMode": "piece"
    }
  ]
};
